import React from "react";
import {motion} from 'framer-motion'
import ProductHero from "../../Components/Producthero/ProductHero";
import GradientCard01 from "../../Components/GradientCard/GradientCard01";

const PreparedDishes = () => {
  return (
    <div className="wrapper-main-product-portfolio">
      <div className="pp-sec-01">
        <ProductHero
          img1={"./ProductPortfolio/p24.jpg"}
          heading={"Wholesome goodness in every serve"}
          img2={"./ProductPortfolio/Artboard 2@5x.webp"}
          url
          overlay
          heading2={' Prepared Dishes and Cooking Aids'}
        />
      </div>
      <div className="chairman-message-wrapper">
        <div className="flex sm:flex-col md:flex-row gap-8 mb-5 col-reverse-small">
        <motion.img initial={{opacity:0}} whileInView={{opacity:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className="w-[55%] object-contain" src="./ProductPortfolio/Artboard 15@3x.webp" alt="" />
        <motion.p initial={{opacity:0}} whileInView={{opacity:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className="big-medium-font">
          The Prepared Dishes and Cooking Aids business recorded a strong growth
          momentum. This was aided by a healthy balance of product mix, pricing
          and volume growth in MAGGI Noodles and MAGGI Masala-ae-Magic,
          supported by strong consumer engagement and market presence with media
          campaigns and attractive consumer activations.
        </motion.p>
        </div>
        
        <motion.p initial={{opacity:0}} whileInView={{opacity:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className="normal-paragraph-container ">
          Exciting new products like MAGGI Oats Noodles with Millet Magic were
          launched to cater to the growing consumer demand for taste and
          balance. The introduction of MAGGI Korean Noodles in Veg and Chicken
          barbeque flavours resonated well with consumers.
          <br />
          Recognizing the unique needs of rural consumers, your Company launched
          MAGGI Teekha Masala and MAGGI Chatpata Masala noodle variants at an
          affordable price of H 10. Your Company also introduced MAGGI Pasta
          Masala, a seasoning to prepare pasta at home.
          <br />
          In a first, the ‘Swad Ke Saath, Quality Ka Bhi Bharosa Pao. Khao Toh
          MAGGI Noodles Khao’ campaign featured real consumer voices from rural
          India to raise awareness about fake Maggi products circulated in the
          market, ensuring consumer protection and brand trust.
          <br />
          <div className="flex sm:flex-col md:flex-row">
<div>
Your Company worked on renewing the recipe for MAGGI Tomato Ketchup
          and it now has 22% less sugar.
          <br />
          Launched on the World Environment Day, the 'Yellow + Blue = Green'
          campaign educated consumers on the proper disposal of plastic
          packaging, emphasizing the importance of recycling. By encouraging
          responsible waste segregation (yellow for plastic, blue for dry
          waste), MAGGI empowered consumers to contribute to a greener future.
          <br />
</div>
<div className="sm:w-full md:w-[100%]">
  <img src="./ProductPortfolio/p24q.webp" alt="" />
</div>
          </div>
         
          In a first-of-its-kind move for the brand, MAGGI introduced
          compostable forks in its cuppa noodles. This initiative reduces
          plastic waste generated by single-use utensils, demonstrating MAGGI's
          commitment to sustainable packaging solutions. The focus on consumer
          delight, strong execution, and commitment to sustainability
          contributed to the sale of over six billion servings of MAGGI during
          the year, making India the largest Nestlé market for MAGGI worldwide.
         <div className="flex sm:flex-col md:flex-row gap-8">
         <GradientCard01
            bigData={"6 billion+"}
            smallData={"serves of MAGGI sold"}
          />
          <GradientCard01
            bigData={"30.4%"}
            smallData={"Contribution to total sales"}
          />
         </div>
         
        </motion.p>
      </div>
      <div className="pp-sec-01">
        <ProductHero
          img1={"./ProductPortfolio/RDP_Munch_People34920_1.jpg"}
          heading={"Beginning every day on a good note"}
          // img2={"./ProductPortfolio/Artboard 8@3x.webp"}
          url
          overlay
          heading2={'Breakfast Cereals'}
        />
      </div>
      <div className="chairman-message-wrapper">
        {/* <h3 className="bold-heading-text text-black font-bold">
          

        </h3> */}
        <motion.p initial={{opacity:0}} whileInView={{opacity:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className="big-medium-font my-3">
          Your Company’s Breakfast Cereals business continued to drive
          penetration with a focus on innovation and exciting new offerings. It
          unveiled two distinct cereals that were designed to cater to a broader
          array of breakfast preferences.
         
        </motion.p>
        <div className="flex sm:flex-col md:flex-row gap-8 col-reverse-small ">
        <motion.img initial={{opacity:0,scale:0.5}} whileInView={{opacity:1,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className="sm:w-full md:w-[70%] object-contain " src="./ProductPortfolio/Artboard 18@3x.webp" alt="" />
        <motion.img initial={{opacity:0,scale:0.5}} whileInView={{opacity:1,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}}  className="sm:w-full md:w-[30%] object-contain " src="./ProductPortfolio/p27.webp" alt="" />
        </div>
        
        <motion.div initial={{opacity:0}} whileInView={{opacity:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className="flex sm:flex-col md:flex-row gap-6 mt-4 justify-between">
          <p className="normal-paragraph-container sm:w-full md:w-[70%]">
            KOKO KRUNCH incorporated local grains like Jowar, blending the
            delightful chocolatey taste of KOKO KRUNCH with the added benefits
            of millets. <br />
            <br />
            For those seeking a more indulgent breakfast option, MUNCH Breakfast
            Cereals is a perfect solution. Crafted with a blend of whole grain
            wheat flour, rice, and corn, this cereal offers a satisfying crunch
            and a delicious way to start the day.
          </p>
          <img
            className="sm:w-full md:w-[30%]"
            src={"./ProductPortfolio/Artboard 19@3x.webp"}
            alt=""
          />
        </motion.div>
      </div>
      <div className="pp-sec-01">
        <ProductHero
          img1={"./ProductPortfolio/p28.jpg"}
          heading={"Unlocking the power of nutrition for pets"}
          img2={"./ProductPortfolio/Artboard 20@3x.webp"}
          url
          overlay
          heading2={'Pet Care'}
        />
      </div>
      <div className="chairman-message-wrapper">
        {/* <h3 className="bold-heading-text text-black font-bold"></h3> */}
        <div className="flex sm:flex-col md:flex-row gap-8">
          <motion.img initial={{opacity:0}} whileInView={{opacity:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className="sm:w-full md:w-[70%]" src="./ProductPortfolio/Artboard 21@3x.webp" alt="" />
        <p className="big-medium-font ">
        The Pet care portfolio which is a part of Prepared Dishes and Cooking Aids business continued to demonstrate its unwavering commitment to enriching the lives of pets. Innovative new products coupled with a strong focus on e-commerce, enabled the portfolio to reach more pet families.
        </p>
        </div>
        
        <br />
        <div className="flex sm:flex-col md:flex-row gap-8">
               <motion.p initial={{opacity:0}} whileInView={{opacity:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className="normal-paragraph-container md:w-[70%] sm:w-full ">
          The portfolio offers a comprehensive array of options catering to both
          canine and feline companions. For dogs, brands such as Purina
          Supercoat and Purina Pro Plan offer complete and balanced dry dog
          food, made with high quality ingredients and no added artificial
          colours or flavours. 
          <br />
          Catering to our feline friends, Purina Friskies continued to be a
          popular dry food choice, while the newly launched Purina Felix wet
          food offered a delectable balance of taste and essential nutrients.
          <br />
          Purina Felix has captured the hearts and taste buds of cats with its
          unique and patented grill technology. This innovative approach
          delivers a taste that cats crave, while offering pet parents a
          convenient wet food option. The positive feedback was instrumental in
          driving trial purchases, paving the way to build a loyal feline
          following.
          <br /> Recognizing the ever-evolving needs of pet owners, your Company
          expanded the reach of the portfolio through e-commerce channels. This
          was proven highly successful, making it easier for pet parents to
          access the food their furry companions love, conveniently delivered
          right to their doorsteps.
        </motion.p>
        <img className="md:w-[30%] sm:w-full object-contain" src="./ProductPortfolio/p29q.webp" alt="" />
        </div>
   
      </div>
    </div>
  )
}

export default PreparedDishes
