import React from 'react'
import ProductHero from '../../Components/Producthero/ProductHero'
import GradientCard01 from '../../Components/GradientCard/GradientCard01'
import {motion} from "framer-motion"
const Planet = () => {
  return (
    <div className='wrapper-main-product-portfolio'>
    <div className="pp-sec-01">
     <ProductHero
       img1={"./Planets/p52.jpg"}
       heading={"Committed to a sustainable future"}
       img2={""}
       heading2={'Planet'}
       url
     />
   </div>
   <div className="chairman-message-wrapper">
     <motion.p initial={{opacity:0,y:"-10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.3}} className="big-medium-font mt-6">
     Your Company’s sustainability commitment focuses on climate change, packaging, responsible sourcing, and water.
        </motion.p>
    <motion.div initial={{opacity:0,y:"-10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} >
    <p className="qus-para">
    Collective action - packaging and waste management
        </p>
       <p className="normal-paragraph-container">
       Your Company has been a pioneer in responsibly managing an amount equivalent to the post-consumer plastic waste generated by its products. Since 2020, its brands have remained plastic neutral. Recognizing the importance of responsible design, your Company is actively transitioning its packaging to mono-material structures that are easy to recycle.
<br />

Your Company continues to reduce its reliance on virgin plastic by minimizing its use where possible. Over the last two years, ~1,800 metric tons of virgin plastic have been eliminated through various initiatives such as replacing plastic straws, using recycled content
in secondary packaging for NESCAFÉ and eliminating overwrap on nutrition products etc. Your Company has also undertaken a unique initiative of making KITKAT and GERBER benches out of recycled plastic.
<br />
Your Company is fully compliant with Plastic Waste Management Rules and has registered as a 'Brand Owner,' ensuring 100% adherence to regulations. It continues to
collaborate with government registered waste management agencies for the end-to-end management of plastic waste. Demonstrating its commitment under Extended Producer Responsibility (EPR), your Company responsibly managed ~25,600 MT of plastic packaging, which was above the EPR target of ~ 23,000 MT assigned by the Central Pollution Control Board.
       </p>
       <div className='flex sm:flex-col md:flex-row gap-8'>
       <GradientCard01
            bigData={"2020"}
            smallData={"Your Company has remained plastic neutral since"}
          />
       <GradientCard01
            bigData={"~25,600"}
            smallData={"MT of EPR"}
          />
       </div>
      
      
    </motion.div>
    <div className='flex my-4 gap-8 sm:flex-col md:flex-row'>
      <div className='md:w-[65%] sm:w-full'>
      <motion.p initial={{opacity:0,y:"-10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.3}} className="qus-para">
    Sustainable sourcing - good food starts with good ingredients
        </motion.p>
        <motion.b initial={{opacity:0,y:"-10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} >Dairy farming</motion.b>
        <motion.p className="normal-paragraph-container">
        Your Company engages with around 80,000 dairy farmers across Punjab, Haryana, Rajasthan and Jammu and Kashmir and is encouraging sustainable dairy farming practices by focusing on transformation and expansion, manure management, feed and fodder management and tree plantation across the value chain. Your Company demonstrated its unwavering commitment towards reducing emissions from the dairy farms through the 'Biodigester Project'. This technology transforms cattle manure
        into clean biogas, reducing the carbon footprint of dairy farms. Approximately 109 large biodigesters and 3,325 small biodigesters have been installed in 24 districts across Punjab and Haryana. More than 550,000 trees were planted in dairy farms to sequester carbon.
        </motion.p>
        <GradientCard01
            bigData={"~80,000"}
            smallData={"Dairy farmers engaged"}
          />
      </div>
     
        <img className='md:w-[40%] sm:w-full object-contain' src="./Planets/Artboard 43@3x.webp" alt="" />
    </div>
    
       
          <motion.div className="video-popup-content mb-6 flex sm:flex-col md:flex-row gap-8">
          <motion.img initial={{opacity:0,scale:0.6}} whileInView={{opacity:1,scale:1}} transition={{duration:0.8,ease:"easeInOut",delay:0.3}} className='sm:w-full lg:w-[48%]' src="./Planets/p54.webp" alt="" />

          <motion.iframe initial={{opacity:0,scale:0.6}} whileInView={{opacity:1,scale:1}} transition={{duration:0.8,ease:"easeInOut",delay:0.1}} className='sm:w-full lg:w-[48%]'  src="https://www.youtube.com/embed/T7oqk5BdITk?si=hAfckgXPW2uxxIoY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></motion.iframe>

              </motion.div>
       <motion.b initial={{opacity:0,y:"-10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}}>Coffee farming</motion.b>  
       <motion.p initial={{opacity:0,y:"-10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className="normal-paragraph-container">The NESCAFÉ Plan is an integrated strategy that leverages regenerative agricultural practices to address GHG emissions, soil health, water conservation and enhance biodiversity. As part of the NESCAFÉ Plan, your Company is engaged with more than 5,000 coffee farmers in sustainable agricultural practices and working towards improving their livelihood. A dedicated network of NESCAFÉ agronomists and supplier resources develop customized sustainability programmes to address the needs of the farmers.

       </motion.p>
       <GradientCard01
            bigData={"5,000+"}
            smallData={"Coffee farmers engaged"}
          />
        <motion.div  className="video-popup-content mb-6 flex sm:flex-col md:flex-row">
        <motion.iframe initial={{opacity:0,scale:0.6}} whileInView={{opacity:1,scale:1}} transition={{duration:0.8,ease:"easeInOut",delay:0.1}} className='sm:w-full lg:w-[48%]' src="https://www.youtube.com/embed/IN0RbOIeL-Y?si=VXSiGSCN0m5UcLoj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></motion.iframe>
        <motion.img initial={{opacity:0,scale:0.6}} whileInView={{opacity:1,scale:1}} transition={{duration:0.8,ease:"easeInOut",delay:0.3}} className='sm:w-full lg:w-[48%]' src="./Planets/p55.webp" alt="" />
        </motion.div>
              <motion.div initial={{opacity:0,scale:0.6}} whileInView={{opacity:1,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className='flex sm:flex-col lg:flex-row gap-8 mb-6'>
              </motion.div>
  <motion.b initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} >MAGGI spice plan</motion.b>
  <motion.p initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className="normal-paragraph-container">Spices are a priority raw material for your Company. We are determined to responsibly source spices from transparent supply chains. Through the MAGGI Spice Plan, your Company locally sources 10 key spices from suppliers across nine states - black pepper, chilli, coriander, cumin, fennel, fenugreek, cardamon, ginger, turmeric and nutmeg are 100% traceable. The MAGGI Spice Plan has trained more than 1,500 spice farmers under the project.
       </motion.p>
       <br />     
  <motion.b initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}}>Rice project</motion.b>
  <motion.p initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className="normal-paragraph-container">Your Company partnered with Bayer Crop Science,
  to embark on a transformative journey to address the critical issue of greenhouse gas (GHG) emissions in paddy cultivation. Besides working on reduction in GHG emissions, the pilot project also aims to improve soil health, protect biodiversity, and support local farmers in dealing with climate change. The project, has registered more than 290 farmers across 31 villages in Jabalpur in Madhya Pradesh and Nizamabad in Telangana.
       </motion.p>
       <GradientCard01
            bigData={"1,500+"}
            smallData={"Spice farmers engaged"}
          />
          <motion.p initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className='qus-para'>Greener deliveries through sustainable logistics</motion.p>
          <motion.img initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className='w-full' src="./Planets/Artboard 41@3x.webp" alt="" />
          <motion.p initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className='normal-paragraph-container mt-4'>Your Company joined forces with 14 other companies as part of the Zero Emission Emerging Markets initiative, a collaborative effort to accelerate the electrification of trucks in the country. By integrating more CNG/LNG and electric vehicles into the fleet, your Company has reduced its reliance on traditional fuels.
            <br />
          There has been a notable rise in railway usage from 0.2% to 6% over the past three years, and an enhanced payload utilization from 90.3% to 93.7% between 2021 and 2023. This has optimized logistics by reducing empty truck journeys and emissions.
          </motion.p>
          <motion.div initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className="flex sm:flex-col lg:flex-row gap-4 mt-6 " >
   <div className='sm:w-full lg:w-[50%]'>
    <b>Increase in railway usage</b>
    <img className='w-full  mt-4' src="./Planets/Screenshot 2024-06-19 at 12.56.25 PM.png" alt="" />
   </div>
   <div className='sm:w-full lg:w-[50%]'>
   <b>Increase in payload utilization</b>
   <img className='w-full mt-4' src="./Planets/Screenshot 2024-06-19 at 12.56.49 PM.png" alt="" />
   </div>

          </motion.div>
          <motion.div initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className="flex sm:flex-col lg:flex-row gap-4 mt-6 p-4" >
   <div className='sm:w-full lg:w-[60%]'>
<p className='qus-para'>Manufacturing gets smarter: cuts waste, boosts sustainability</p>
   <p className='normal-paragraph-container'>
   Your Company has expanded its renewable energy projects across all factories, resulting in a 55.9% reduction in emissions over the past six years (compared to the 2018 baseline).
   </p>
   <motion.img initial={{opacity:0,y:"10px",scale:0.5}} whileInView={{opacity:1,y:0,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} viewport={{once:"true"}} className='w-[40%] mt-4' src="./Planets/Screenshot 2024-06-19 at 12.57.13 PM.png" style={{mixBlendMode:"multiply"}} alt="" />
   </div>
   <div className='sm:w-full lg:w-[40%]'>
   <p className='normal-paragraph-container mt-4'>Biomass boilers have been installed in Nanjangud, Moga, and Sanand factories for steam generation and GHG emissions reduction, and the usage of coal has been eliminated from eight factories.
   Continuous efforts have been made at the factories to minimize the consumption of natural resources and reduce water, energy, and carbon emissions while maximizing production volumes. Over the last 15 years (2008-2024), your Company has, on an average, reduced energy usage by around 29% per ton of production, water usage by around 46% per ton of production, generation of wastewater by around 60% per ton of production, and specific direct and indirect greenhouse gas emissions by 61% per ton of production.</p>
   </div>

          </motion.div>
          <motion.div  className="flex sm:flex-col lg:flex-row gap-4 mt-6 p-4 bg-slate-100 "  >
   <motion.div initial={{opacity:0,y:"10px",scale:0.5}} whileInView={{opacity:1,y:0,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className='sm:w-full lg:w-[16%]'>
    <img style={{mixBlendMode:"darken"}} className='lg:w-full sm:w-[50%] m-auto p-4' src="./Planets/Screenshot 2024-06-19 at 12.57.34 PM.png" alt="" />
   </motion.div>
   <motion.div initial={{opacity:0,y:"10px",scale:0.5}} whileInView={{opacity:1,y:0,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.1}} className='sm:w-full lg:w-[16%]'>
   <img style={{mixBlendMode:"multiply"}} className='lg:w-full sm:w-[50%] m-auto p-4' src="./Planets/Screenshot 2024-06-19 at 12.58.14 PM.png" alt="" />
   </motion.div>

   <motion.div initial={{opacity:0,y:"10px",scale:0.5}} whileInView={{opacity:1,y:0,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.2}} className='sm:w-full lg:w-[16%]'>
   <img style={{mixBlendMode:"multiply"}} className='lg:w-full sm:w-[50%] m-auto p-4' src="./Planets/Screenshot 2024-06-19 at 12.58.37 PM.png" alt="" />
   </motion.div>

   <motion.div initial={{opacity:0,y:"10px",scale:0.5}} whileInView={{opacity:1,y:0,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.3}} className='sm:w-full lg:w-[16%]'>
   <img style={{mixBlendMode:"multiply"}} className='lg:w-full sm:w-[20%] m-auto p-4' src="./Planets/Screenshot 2024-06-19 at 12.58.47 PM.png" alt="" />
   </motion.div>
   <div className='sm:w-full lg:w-[30%]'>
  <p className='normal-paragraph-container mt-2'>A significant step has been taken towards water conservation projects across all factories, reducing water withdrawal intensity by 27.4% compared to the 2018 baseline.</p>
  <motion.img initial={{opacity:0,y:"10px",scale:0.5}} whileInView={{opacity:1,y:0,scale:1}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} style={{mixBlendMode:"multiply"}} className='w-[80%] mt-4' src="./Planets/Screenshot 2024-06-19 at 12.59.04 PM.png" alt="" />
   </div>
          </motion.div>
          <motion.p initial={{opacity:0,y:"10px"}} whileInView={{opacity:1,y:0}} transition={{duration:0.5,ease:"easeInOut",delay:0.4}} className='normal-paragraph-container'>Your Company is harnessing technology to reduce
          its reliance on groundwater. Through the successful implementation of Zer'Eau technology in Moga and Samalkha factories, water extracted from milk is recycled to reduce groundwater consumption every year.
          </motion.p>
     </div>
 </div>
  )
}

export default Planet
